- hosts: controller
  tasks: 
  - name: Install MySQL Packages
    apt: pkg={{item}} state=installed
    with_items:
      - mysql-server
      - python-mysqldb

  - name: Set root password
    mysql_user: name=root password=openstack host="{{item}}" priv=*.*:ALL,GRANT state=present
    with_items:
      - "{{ansible_hostname}}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Create .my.cnf file with root password credentials
    template: src=templates/mysql/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: Restart the MySQL service
    action: service name=mysql state=restarted enabled=true

  - name: Create MySQL configuration file
    template: src=templates/mysql/mysqld_openstack.cnf.j2 dest=/etc/mysql/conf.d/mysqld_openstack.cnf 

